
name: Build NDK (Win)

on:
  workflow_call:

jobs:
  build-ndk-win:
    runs-on: [ self-hosted, Windows, X64, w10-1344 ]
    steps:
    - uses: actions/checkout@v2
    - name: git-update-dependecies
      run: git submodule update --init --recursive
    - name: Find NDK SHA
      run: |
        $INWORLD_NDK_SHA=(git submodule status).Trim().Split()[0]
        echo $INWORLD_NDK_SHA
        Add-Content -Path ${env:GITHUB_ENV} -Value "INWORLD_NDK_SHA=$INWORLD_NDK_SHA"
    - uses: actions/cache/restore@v3
      id: ndk-cache-win64
      with:
        path: InworldAI\inworld-ndk\build\Package
        key: ${{ runner.OS }}-ndk-cache-Win64-${{ env.INWORLD_NDK_SHA }}
    - name: Build NDK (Win64)
      shell: pwsh
      if: steps.ndk-cache-win64.outputs.cache-hit != 'true'
      run: |
        $process = Start-Process -FilePath "C:\Program Files\Python310\Python.exe" -Wait -NoNewWindow -PassThru -ArgumentList InworldAI\Source\ThirdParty\Inworld\dev-tools\ndk-util.py,--platform=Win64,--clean,--build
        if($process.ExitCode -ne 0)
        {
          exit 1
        }
    - uses: actions/cache/save@v3
      if: steps.ndk-cache-win64.outputs.cache-hit != 'true'
      with:
        path: InworldAI\inworld-ndk\build\Package
        key: ${{ runner.OS }}-ndk-cache-Win64-${{ env.INWORLD_NDK_SHA }}
