
name: Build Win UE.5.0

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/gitignore'
  workflow_dispatch:

jobs:
  build-ndk-win:
    uses: ./.github/workflows/build-ndk-win.yml

  build-win-50:
    runs-on: [ self-hosted, Windows, X64, w10-1344 ]
    needs: [ build-ndk-win ]
    steps:
    - uses: actions/checkout@v2
    - name: git-update-dependecies
      run: git submodule update --init --recursive | Write-Host
    - name: Find NDK SHA
      run: |
        $INWORLD_NDK_SHA=(git submodule status).Trim().Split()[0]
        echo $INWORLD_NDK_SHA
        Add-Content -Path ${env:GITHUB_ENV} -Value "INWORLD_NDK_SHA=$INWORLD_NDK_SHA"
    - uses: actions/cache/restore@v3
      id: ndk-cache-win64
      with:
        path: InworldAI\inworld-ndk\build\Package
        key: ${{ runner.OS }}-ndk-cache-Win64-${{ env.INWORLD_NDK_SHA }}
        fail-on-cache-miss: true
    - name: Copy NDK
      run: |
          $process = Start-Process -FilePath "C:\Program Files\Python310\Python.exe" -Wait -NoNewWindow -PassThru -ArgumentList InworldAI\Source\ThirdParty\Inworld\dev-tools\ndk-util.py,--copy
          if($process.ExitCode -ne 0)
          {
            exit 1
          }
    - run: mkdir -p TestInworldFPS 
    - uses: actions/checkout@v2
      with:
        ref: 'TestInworldFPS'
        path: 'TestInworldFPS'
    - name: Copy Plugins & Remove Assets
      shell: pwsh
      run: |
          Remove-Item "InworldAI\Content\*" -Recurse -ErrorAction SilentlyContinue
          Remove-Item "TestInworldFPS\TestInworldFPS\Plugins\InworldAI" -Recurse -ErrorAction SilentlyContinue
          Remove-Item "TestInworldFPS\TestInworldFPS\Plugins\InworldMetahuman" -Recurse -ErrorAction SilentlyContinue
          Remove-Item "TestInworldFPS\TestInworldFPS\Plugins\InworldReadyPlayerMe" -Recurse -ErrorAction SilentlyContinue
          Copy-Item -Path "InworldAI"  -Destination "TestInworldFPS\TestInworldFPS\Plugins\InworldAI" -Recurse
          Copy-Item -Path "InworldMetahuman"  -Destination "TestInworldFPS\TestInworldFPS\Plugins\InworldMetahuman" -Recurse
          Copy-Item -Path "InworldReadyPlayerMe"  -Destination "TestInworldFPS\TestInworldFPS\Plugins\InworldReadyPlayerMe" -Recurse
    - name: BuildEditor-Win-50
      shell: pwsh
      run: |
          [string]$UEPath = "C:\Program Files\Epic Games\UE_5.0"
          [string]$ProjectPath = "$pwd"
          Start-Process -FilePath "$UEPath\Engine\Build\BatchFiles\RunUAT.bat" -ArgumentList BuildEditor,-Project="$ProjectPath\TestInworldFPS\TestInworldFPS\TestInworldFPS.uproject",-platform=Win64,-notools,-configuration=Development+Shipping," > BuildEditorLog.txt" -Wait -NoNewWindow -PassThru
          cat BuildEditorLog.txt
          if (Select-String -Path BuildEditorLog.txt -Pattern "BUILD SUCCESSFUL" -SimpleMatch -Quiet)
          {
            exit 0
          }
          else
          {
            exit 1
          }
    - name: BuildGame-Win-50
      shell: pwsh
      run: |
          [string]$UEPath = "C:\Program Files\Epic Games\UE_5.0"
          [string]$ProjectPath = "$pwd"
          Start-Process -FilePath "$UEPath\Engine\Build\BatchFiles\RunUAT.bat" -ArgumentList BuildGame,-Project="$ProjectPath\TestInworldFPS\TestInworldFPS\TestInworldFPS.uproject",-platform=Win64,-notools,-configuration=Development+Shipping," > BuildGameLog.txt" -Wait -NoNewWindow -PassThru
          cat BuildGameLog.txt
          if (Select-String -Path BuildGameLog.txt -Pattern "BUILD SUCCESSFUL" -SimpleMatch -Quiet)
          {
            exit 0
          }
          else
          {
            exit 1
          }
    - name: BuildPlugin-Win-50
      shell: pwsh
      run: |
          [string]$UEPath = "C:\Program Files\Epic Games\UE_5.0"
          [string]$ProjectPath = "$pwd"
          Start-Process -FilePath "$UEPath\Engine\Build\BatchFiles\RunUAT.bat" -ArgumentList BuildPlugin,-plugin="$ProjectPath\TestInworldFPS\TestInworldFPS\Plugins\InworldAI\InworldAI.uplugin",-TargetPlatforms=Win64,-package="$ProjectPath\PluginBuild"," > BuildPluginLog.txt" -Wait -NoNewWindow -PassThru
          cat BuildPluginLog.txt
          if (Select-String -Path BuildPluginLog.txt -Pattern "BUILD SUCCESSFUL" -SimpleMatch -Quiet)
          {
            exit 0
          }
          else
          {
            exit 1
          }
