
name: Build SDK (iOS)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-ios:
    strategy:
      matrix:
        ue-version: ['5.1']
    runs-on: [ self-hosted, macOS, ARM64, m1-1317 ]
    steps:
    - uses: actions/checkout@v4
    - name: git-update-dependecies
      run: git submodule update --init --recursive
    - uses: actions/download-artifact@v4
      with:
        name: NDK-iOS
        path: InworldAI/Source/ThirdParty/InworldAINDKLibrary
    - name: Copy NDK
      run: |
        python3 "build-scripts/ndk-util.py" --copy
    - name: Copy Template - First Person
      shell: bash
      run: |
          cp -r "/Users/Shared/Epic Games/UE_${{ matrix.ue-version }}/Templates/TP_FirstPerson" "TP_FirstPerson"
    - name: Copy Plugins & Remove Assets
      shell: bash
      run: |
          rm -rf "InworldAI/Content"
          rm -rf "InworldAI/inworld-ndk"
          rm -rf "TP_FirstPerson/Plugins/InworldAI"
          mkdir "TP_FirstPerson/Plugins"
          cp -r "InworldAI" "TP_FirstPerson/Plugins"
    - name: BuildGame-ios-${{ matrix.ue-version }}
      shell: bash
      run: |
          sh "/Users/Shared/Epic Games/UE_${{ matrix.ue-version }}/Engine/Build/BatchFiles/RunUAT.sh" > BuildGameLog.txt BuildGame -project="$PWD/TP_FirstPerson/TP_FirstPerson.uproject" -platform=IOS  -notools -configuration=Development+Shipping
          cat BuildGameLog.txt
          if (grep -Fxq "BUILD SUCCESSFUL" BuildGameLog.txt)
          then
              exit 0
          fi
          exit 1
    - name: BuildPlugin-ios-${{ matrix.ue-version }}
      shell: bash
      run: |
        sh "/Users/Shared/Epic Games/UE_${{ matrix.ue-version }}/Engine/Build/BatchFiles/RunUAT.sh" > BuildPluginLog.txt BuildPlugin -plugin="$PWD/TP_FirstPerson/Plugins/InworldAI/InworldAI.uplugin" -TargetPlatforms=IOS -package="$PWD/PluginBuild"
        cat BuildPluginLog.txt
          if (grep -Fxq "BUILD SUCCESSFUL" BuildPluginLog.txt)
          then
              exit 0
          fi
          exit 1
