
name: Build SDK (MacOS)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-mac:
    strategy:
      matrix:
        ue-version: ['5.1']
    runs-on: [ self-hosted, macOS, ARM64, m1-1317 ]
    steps:
    - uses: actions/checkout@v4
    - name: git-update-dependecies
      run: git submodule update --init --recursive
    - name: Find NDK SHA
      run: |
        INWORLD_NDK_SHA=$(git submodule status | cut -d " " -f 2)
        echo $INWORLD_NDK_SHA
        echo "INWORLD_NDK_SHA=$INWORLD_NDK_SHA" >> $GITHUB_ENV
    - uses: actions/cache/restore@v4
      id: ndk-cache-mac
      with:
        path: InworldAI/inworld-ndk/build/Package
        key: ndk-cache-Mac-${{ env.INWORLD_NDK_SHA }}
        fail-on-cache-miss: true
        enableCrossOsArchive: true
    - name: check-cache-success
      if: steps.ndk-cache-mac.outputs.cache-hit != 'true'
      run: |
        echo "cache restore failed"
        exit 1
    - name: Copy NDK
      run: |
        python3 "build-scripts/ndk-util.py" --copy
    - name: Copy Template - First Person
      shell: bash
      run: |
          cp -r "/Users/Shared/Epic Games/UE_${{ matrix.ue-version }}/Templates/TP_FirstPerson" "TP_FirstPerson"
    - name: Copy Plugins & Remove Assets
      shell: bash
      run: |
          rm -rf "InworldAI/Content"
          rm -rf "TP_FirstPerson/Plugins/InworldAI"
          rm -rf "TP_FirstPerson/Plugins/InworldMetahuman"
          rm -rf "TP_FirstPerson/Plugins/InworldInnequin"
          mkdir "TP_FirstPerson/Plugins"
          cp -r "InworldAI" "TP_FirstPerson/Plugins"
          cp -r "InworldMetahuman" "TP_FirstPerson/Plugins"
          cp -r "InworldInnequin" "TP_FirstPerson/Plugins"
    - name: BuildEditor-Mac-51
      shell: bash
      run: |
          sh "/Users/Shared/Epic Games/UE_${{ matrix.ue-version }}/Engine/Build/BatchFiles/RunUAT.sh" > BuildEditorLog.txt BuildEditor -project="$PWD/TP_FirstPerson/TP_FirstPerson.uproject" -platform=Mac  -notools -configuration=Development+Shipping
          cat BuildEditorLog.txt
          if (grep -Fxq "BUILD SUCCESSFUL" BuildEditorLog.txt)
          then
              exit 0
          fi
          exit 1
    - name: BuildGame-Mac-51
      shell: bash
      run: |
          sh "/Users/Shared/Epic Games/UE_${{ matrix.ue-version }}/Engine/Build/BatchFiles/RunUAT.sh" > BuildGameLog.txt BuildGame -project="$PWD/TP_FirstPerson/TP_FirstPerson.uproject" -platform=Mac -notools -configuration=Development+Shipping
          cat BuildGameLog.txt
          if (grep -Fxq "BUILD SUCCESSFUL" BuildGameLog.txt)
          then
              exit 0
          fi
          exit 1
    - name: BuildPlugin-Mac-51
      shell: bash
      run: |
        sh "/Users/Shared/Epic Games/UE_${{ matrix.ue-version }}/Engine/Build/BatchFiles/RunUAT.sh" > BuildPluginLog.txt BuildPlugin -plugin="$PWD/TP_FirstPerson/Plugins/InworldAI/InworldAI.uplugin" -TargetPlatforms=Mac -package="$PWD/PluginBuild"
        cat BuildPluginLog.txt
          if (grep -Fxq "BUILD SUCCESSFUL" BuildPluginLog.txt)
          then
              exit 0
          fi
          exit 1
