
name: Build NDK (Android)

on:
  workflow_call:

jobs:
  build-ndk-android:
    runs-on: [ self-hosted, macOS, ARM64, m1-1317 ]
    steps:
    - uses: actions/checkout@v2
    - name: git-update-dependecies
      run: git submodule update --init
    - name: Find NDK SHA
      run: |
        INWORLD_NDK_SHA=$(git submodule status | cut -d " " -f 2)
        echo $INWORLD_NDK_SHA
        echo "INWORLD_NDK_SHA=$INWORLD_NDK_SHA" >> $GITHUB_ENV
    - uses: actions/cache/restore@v3
      id: ndk-cache-android
      with:
        path: InworldAI/inworld-ndk/build/Package
        key: ndk-cache-Android-${{ env.INWORLD_NDK_SHA }}
        enableCrossOsArchive: true
    - name: git-update-dependecies
      if: steps.ndk-cache-android.outputs.cache-hit != 'true'
      run: git submodule update --init --recursive
    - name: Build NDK (Android)
      shell: bash
      if: steps.ndk-cache-android.outputs.cache-hit != 'true'
      run: |
        python3 "build-scripts/ndk-util.py" --platform=Android --clean --build
        rm InworldAI/inworld-ndk/build/CMakeCache.txt
        python3 "build-scripts/ndk-util.py" --platform=Android-shared --build
    - uses: actions/cache/save@v3
      if: steps.ndk-cache-android.outputs.cache-hit != 'true'
      with:
        path: InworldAI/inworld-ndk/build/Package
        key: ndk-cache-Android-${{ env.INWORLD_NDK_SHA }}
        enableCrossOsArchive: true
