// Copyright 2023 Theai, Inc. (DBA Inworld) All Rights Reserved.

name: Check license header

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'

jobs:
  ##approved:
  ##  if: github.event.review.state == 'approved'
  ##  runs-on: ubuntu-latest
  ##  steps:
  ##    - run: echo "This PR was approved"

  check_header:
    ##needs: [approved]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check License Header
      uses: apache/skywalking-eyes@v0.4.0
      with:
        mode: check
