
name: Package

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/gitignore'
      - '**/LICENSE.md'
      - '.github/workflows/release.yml'
  workflow_call:
  workflow_dispatch:

jobs:
  build-ndk-win:
    uses: ./.github/workflows/build-ndk-win.yml
  build-ndk-mac:
    uses: ./.github/workflows/build-ndk-mac.yml
  build-ndk-ios:
    uses: ./.github/workflows/build-ndk-ios.yml
  build-ndk-android:
    uses: ./.github/workflows/build-ndk-android.yml

  upload-ndk:
    strategy:
      matrix:
        os: ['Win64', 'Mac', 'iOS', 'Android']
    runs-on: ubuntu-latest
    needs: [ build-ndk-win, build-ndk-mac, build-ndk-ios, build-ndk-android ]
    env:
        os: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: git-update-dependecies
      run: git submodule update --init
    - name: Find NDK SHA
      run: |
        INWORLD_NDK_SHA=$(git submodule status | cut -d " " -f 2)
        echo $INWORLD_NDK_SHA
        echo "INWORLD_NDK_SHA=$INWORLD_NDK_SHA" >> $GITHUB_ENV
    - uses: actions/cache/restore@v3
      id: ndk-cache-${{ env.os }}
      with:
        path: InworldAI/inworld-ndk/build/Package
        key: ndk-cache-${{ env.os }}-${{ env.INWORLD_NDK_SHA }}
        fail-on-cache-miss: true
    - uses: actions/upload-artifact@v3
      with:
        name: NDK-Source
        path: |
          InworldAI\inworld-ndk\build\Package
          !InworldAI\inworld-ndk\build\Package\lib
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.os }}-NDK-lib
        path: InworldAI/inworld-ndk/build/Package/lib/${{ env.os }}

  build-sdk-win:
    needs: [ build-ndk-win ]
    uses: ./.github/workflows/build-sdk-win.yml
  build-sdk-android:
    needs: [ build-ndk-android, build-ndk-win ]
    uses: ./.github/workflows/build-sdk-android.yml
  build-sdk-mac:
    needs: [ build-ndk-mac ]
    uses: ./.github/workflows/build-sdk-mac.yml
  build-sdk-ios:
    needs: [ build-ndk-ios, build-ndk-mac ]
    uses: ./.github/workflows/build-sdk-ios.yml

  package:
    runs-on: ubuntu-latest
    needs: [ build-sdk-win, build-sdk-android, build-sdk-mac, build-sdk-ios, upload-ndk ]
    steps:
      - uses: actions/checkout@v2
      - name: git-update-dependecies
        run: git submodule update --init --recursive
      - uses: actions/download-artifact@v3
        with:
          name: NDK-Source
          path: InworldAI/Source/ThirdParty/InworldAINDKLibrary
      - uses: actions/download-artifact@v3
        with:
          name: Win-NDK-lib
          path: InworldAI/Source/ThirdParty/InworldAINDKLibrary/lib/Win64
      - uses: actions/download-artifact@v3
        with:
          name: Mac-NDK-lib
          path: InworldAI/Source/ThirdParty/InworldAINDKLibrary/lib/Mac
      - uses: actions/download-artifact@v3
        with:
          name: iOS-NDK-lib
          path: InworldAI/Source/ThirdParty/InworldAINDKLibrary/lib/iOS
      - uses: actions/download-artifact@v3
        with:
          name: Android-NDK-lib
          path: InworldAI/Source/ThirdParty/InworldAINDKLibrary/lib/Android
      - uses: actions/upload-artifact@v3
        with:
          name: inworld-unreal-sdk
          path: |
            InworldAI
            !InworldAI/inworld-ndk
      - uses: actions/upload-artifact@v3
        with:
          name: inworld-unreal-sdk-innequin
          path: InworldInnequin
      - uses: actions/upload-artifact@v3
        with:
          name: inworld-unreal-sdk-metahuman
          path: InworldMetahuman
