
name: Package

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/gitignore'
      - '**/LICENSE.md'
      - '.github/workflows/release.yml'
  workflow_call:
  workflow_dispatch:

jobs:
  build-ndk-win:
    uses: ./.github/workflows/build-ndk-win.yml
  build-ndk-mac:
    uses: ./.github/workflows/build-ndk-mac.yml
  build-ndk-ios:
    uses: ./.github/workflows/build-ndk-ios.yml
  build-ndk-android:
    uses: ./.github/workflows/build-ndk-android.yml

  upload-ndk-win:
    needs: [ build-ndk-win ]
    uses: ./.github/workflows/upload-ndk-win.yml
  upload-ndk-android:
    needs: [ build-ndk-android ]
    uses: ./.github/workflows/upload-ndk-android.yml
  upload-ndk-mac:
    needs: [ build-ndk-mac ]
    uses: ./.github/workflows/upload-ndk-mac.yml
  upload-ndk-ios:
    needs: [ build-ndk-ios ]
    uses: ./.github/workflows/upload-ndk-ios.yml

  build-sdk-win:
    needs: [ upload-ndk-win ]
    uses: ./.github/workflows/build-sdk-win.yml
  build-sdk-android:
    needs: [ upload-ndk-android ]
    uses: ./.github/workflows/build-sdk-android.yml
  build-sdk-mac:
    needs: [ upload-ndk-mac ]
    uses: ./.github/workflows/build-sdk-mac.yml
  build-sdk-ios:
    needs: [ upload-ndk-ios ]
    uses: ./.github/workflows/build-sdk-ios.yml

  package:
    runs-on: ubuntu-latest
    needs: [ upload-ndk-win, upload-ndk-android, upload-ndk-mac, upload-ndk-ios ]
    steps:
      - uses: actions/checkout@v4
      - name: git-update-dependecies
        run: git submodule update --init --recursive
      - uses: actions/download-artifact@v3
        with:
          name: NDK-Source
          path: InworldAI/Source/ThirdParty/InworldAINDKLibrary
      - uses: actions/download-artifact@v3
        with:
          name: Win-NDK-lib
          path: InworldAI/Source/ThirdParty/InworldAINDKLibrary/lib/Win64
      - uses: actions/download-artifact@v3
        with:
          name: Mac-NDK-lib
          path: InworldAI/Source/ThirdParty/InworldAINDKLibrary/lib/Mac
      - uses: actions/download-artifact@v3
        with:
          name: iOS-NDK-lib
          path: InworldAI/Source/ThirdParty/InworldAINDKLibrary/lib/iOS
      - uses: actions/download-artifact@v3
        with:
          name: Android-NDK-lib
          path: InworldAI/Source/ThirdParty/InworldAINDKLibrary/lib/Android
      - uses: actions/upload-artifact@v3
        with:
          name: inworld-unreal-sdk
          path: |
            InworldAI
            !InworldAI/inworld-ndk
      - uses: actions/upload-artifact@v3
        with:
          name: inworld-unreal-sdk-innequin
          path: InworldInnequin
      - uses: actions/upload-artifact@v3
        with:
          name: inworld-unreal-sdk-metahuman
          path: InworldMetahuman
