
name: Package

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/gitignore'
      - '**/LICENSE.md'
      - '.github/workflows/release.yml'
  workflow_call:
  workflow_dispatch:

jobs:
  build-ndk-win:
    uses: ./.github/workflows/build-ndk-win.yml
  build-ndk-mac:
    uses: ./.github/workflows/build-ndk-mac.yml
  build-ndk-ios:
    uses: ./.github/workflows/build-ndk-ios.yml
  build-ndk-android:
    uses: ./.github/workflows/build-ndk-android.yml

  build-sdk-win:
    needs: [ build-ndk-win ]
    uses: ./.github/workflows/build-sdk-win.yml
  build-sdk-android:
    needs: [ build-ndk-win, build-ndk-android ]
    uses: ./.github/workflows/build-sdk-android.yml
  build-sdk-mac:
    needs: [ build-ndk-mac ]
    uses: ./.github/workflows/build-sdk-mac.yml
  build-sdk-ios:
    needs: [ build-ndk-mac, build-ndk-ios ]
    uses: ./.github/workflows/build-sdk-ios.yml

  package:
    runs-on: ubuntu-latest
    needs: [ build-sdk-win, build-sdk-android, build-sdk-mac, build-sdk-ios ]
    steps:
      - uses: actions/checkout@v4
      - name: git-update-dependecies
        run: git submodule update --init --recursive
      - name: Merge NDK Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: inworld-ndk
          pattern: NDK-*
          delete-merged: true
      - uses: actions/download-artifact@v4
        with:
          name: inworld-ndk
          path: InworldAI/Source/ThirdParty/InworldAINDKLibrary
      - uses: actions/upload-artifact@v4
        with:
          name: inworld-unreal-sdk
          path: |
            InworldAI
            !InworldAI/inworld-ndk
      - uses: actions/upload-artifact@v4
        with:
          name: inworld-unreal-sdk-innequin
          path: InworldInnequin
      - uses: actions/upload-artifact@v4
        with:
          name: inworld-unreal-sdk-metahuman
          path: InworldMetahuman
