
name: Upload NDK (Win)

on:
  workflow_call:

jobs:
  upload-ndk-win:
    runs-on: [ self-hosted, Windows, X64, w10-1344 ]
    steps:
    - name: Find NDK SHA
      run: |
        $INWORLD_NDK_SHA=(git submodule status).Trim().Split()[0]
        echo $INWORLD_NDK_SHA
        Add-Content -Path ${env:GITHUB_ENV} -Value "INWORLD_NDK_SHA=$INWORLD_NDK_SHA"
    - uses: actions/cache/restore@v4
      id: ndk-cache-win64
      with:
        path: InworldAI\inworld-ndk\build\Package
        key: ndk-cache-Win64-${{ env.INWORLD_NDK_SHA }}
        enableCrossOsArchive: true
        fail-on-cache-miss: true
    - uses: actions/upload-artifact@v4
      with:
        name: NDK-Win
        path: |
          InworldAI\inworld-ndk\build\Package      
